openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: 'http://localhost:8080'
    description: Generated server url
paths:
  /magic:
    post:
      tags:
        - magic-_8_-ball-controller
      operationId: createMagic
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Magic_8_Ball'
        required: true
      responses:
        '201':
          description: Created
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Magic_8_Ball'
  /word:
    get:
      tags:
        - word-controller
      operationId: getWord
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Word'
  /quote:
    get:
      tags:
        - quote-controller
      operationId: getQuote
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Quote'
components:
  schemas:
    Magic_8_Ball:
      type: object
      properties:
        question:
          type: string
        answer:
          type: string
        id:
          type: integer
          format: int32
    Word:
      type: object
      properties:
        id:
          type: integer
          format: int32
        word:
          type: string
        definition:
          type: string
    Quote:
      type: object
      properties:
        author:
          type: string
        quote:
          type: string
        id:
          type: integer
          format: int32
